development:
    adapter: postgresql
    encoding: unicode
    database: lockdown_development
    pool: 5
    username:
    password:

test:
    adapter: postgresql
    encoding: unicode
    database: lockdown_test
    pool: 5
    username:
    password:
